### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Video unavailable

### ISSUE THREAD

**Issue by mxArkel86** [NicholasLKSharp/DiscordJSMusicBot-SpotifyPuller#1]
(node:6976) UnhandledPromiseRejectionWarning: Error: Video unavailable
    at Object.exports.playError (g:\DiscordMusicBot\node_modules\ytdl-core\lib\util.js:444:12)
    at downloadFromInfoCallback (g:\DiscordMusicBot\node_modules\ytdl-core\lib\index.js:58:18)
    at g:\DiscordMusicBot\node_modules\ytdl-core\lib\index.js:18:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
<node_internals>/internal/process/warning.js:32

An error that happens during the download process of the music using the ytdl-core library. Error goes through catch exception and seems to be semi-random in when it happens and to what songs.

**Comment by mxArkel86** [comment]
turns out the error was from not including an error listener on the ytdl-core download process. A try statement was not able to bypass it.
